### ISSUE TITLE
Import button is showing up, even if there is nothing to import

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-ldapuserimport#14]
This happens:

- before searching.. Nothing is displayed but there is the Import button
- if there are no results
- after importing 

Ideally there should be "Close" button instead, especially after importing

**Comment by acotiuga** [comment]
For this I would propose to only display the import button when there is something to import and to not display or replace it at all. There are already 2 options to close/cancel, so a third one would be too much:
![Screenshot from 2021-02-22 11-38-25](https://user-images.githubusercontent.com/8121819/108690240-ca56c280-7502-11eb-8e89-4a6fcd56d450.png)
