### ISSUE TITLE
The display of the button to import a user in the context of a group is not consistent between the different places where it's displayed

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-ldapuserimport#20]
When navigating to the page of the group, an "Import users" button is displayed under the users table, in both view and edit mode:

View:
![image](https://user-images.githubusercontent.com/657716/109635363-9014a300-7b4a-11eb-8a08-b81a8983028a.png)

Edit:
![image](https://user-images.githubusercontent.com/657716/109635415-9efb5580-7b4a-11eb-8ec2-8844daf83035.png)

However, when editing a group from the administration of the wiki, from the groups table (by clicking on the edit button), the import button is displayed next to the inputs allowing to select an existing user from the wiki:

![image](https://user-images.githubusercontent.com/657716/109635554-d0742100-7b4a-11eb-8735-b66124d2aa0b.png)

There are 2 aspects of the currently reported issue:
* the display should be coherent in both cases, for efficient user experience
* my preference goes for the display from the administration, it presents the import button as an alternative to searching for an existing user on the wiki, which is what this button is

**Comment by acotiuga** [comment]
1. In Group page, view mode:
![groupPageViewMode](https://user-images.githubusercontent.com/8121819/110083180-0d345800-7d97-11eb-9d2d-cfd822f2b5d0.png)

2. In Group page, edit mode:
![groupPageEditMode](https://user-images.githubusercontent.com/8121819/110083203-13c2cf80-7d97-11eb-8fa9-25b64532962b.png)

3. In edit Group modal:
![editGroupModal](https://user-images.githubusercontent.com/8121819/110083219-19b8b080-7d97-11eb-833b-cbe8743dd929.png)
