### ISSUE TITLE
Enter key in the search user input does not launch the search

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-ldapuserimport#29]
How to reproduce:
* go on a group page
* click edit
* click import users
* in the displayed popup, fill in a search string
* hit the enter key
![image](https://user-images.githubusercontent.com/657716/112463956-2b242580-8d63-11eb-8811-f1b8552682b1.png)

Expected result:
* the search should be launched by the enter key and the search results displayed

Actual result
* the "search" button neds to be actioned specifically: clicked with the mouse or navigated to with the tab key and actioned there

**Comment by lucaa** [comment]
This is a minor issue, I didn't find the label to set the label there.

**Comment by lucaa** [comment]
Technically it probably can be fixed from the forms markup, on this screen there should actually be 2 forms:
* the search form that has the search input as input and the "Search" button that is the submit button of this form
* the import form, whose submit button is the "import" button and the inputs are the users checkboxes. The users checkboxes are created/filled in by the results of the search form.

**Comment by acotiuga** [comment]
New look of the import users modal, the 2 forms for searching and importing users are fully aligned and so their submit buttons. 
In the modal footer, there in only the cancel button.
![searchUsers](https://user-images.githubusercontent.com/8121819/115403950-8b3ca900-a1f5-11eb-894c-96cec4b0497a.png)
