### ISSUE TITLE
No feedback on the screen when the import is ongoing: import can be launched multiple times while it's ongoing

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-ldapuserimport#30]
How to reproduce:
* go to a group page
* click edit
* click import users
* in the popup, fill in a search that will yield results
* in the results, check some box to import some users
* click the "Import" button
![image](https://user-images.githubusercontent.com/657716/112466050-b1416b80-8d65-11eb-8629-7c67f835748f.png)

Expected result: 
* There should be some feedback on the screen that the import has started and it's ongoing (that the Import button actually worked)

Actual result
* Nothing changes on the screen at this point, it's not clear whether the button worked or not, whether the import started or not.
* In addition, the Import button remains usable, and can be clicked as many times as one wants - it's very probable for this to happen as there is no feedback on the screen that the first click was actually taken into account but it also depends on how long the import takes (this may be related to various server settings but also to the speed of the internet connection on the client)
  * If the button is clicked multiple times, at some point (when the multiple imports finish), there are a couple of messages displayed in the popup, that replace eachother, some are saying success, some are saying error
  * In any case, at the end of all this (when popup is closed) the user appears multiple times in the group, but with the same username (which was blurred on this screenshot) - later edit: they're not all with the same username, see comment below:

![image](https://user-images.githubusercontent.com/657716/112466504-417fb080-8d66-11eb-8d57-e710b3e8653c.png)

**Comment by lucaa** [comment]
Regardless of how the feedback that something is ongoing is given to the user, the Import button needs to be disabled when an import is ongoing and re-enabled (if needed) when the import request returns. 

This also works as at least some partial feedback to the user that the click on the import button was actually taken into account and something has happened, but the best for the feedback would be to check how other similar situations are handled in popups in XWiki (notifications, other?) and apply that technique.

Even best would be to actually check what happens on the server when such an import is launched multiple times and make sure its safely handled (the same user _may_ endup imported in 2 different groups by 2 different admins, and in theory this can happen exactly at the same time) - but this is much much more advanced and can be handled as a separate issue.

**Comment by lucaa** [comment]
> [...] the user appears multiple times in the group, but with the same username [...]

Actually, after playing around a bit more with this bug, I somehow managed to create a second user, at some point, with a username of the form <username>_1 where username is the username that was used to import the user. 
I checked the history of that user (the _1 one ) and it is marked in the history as imported from LDAP.

I don't know exactly how I did it, probably race condition, so regading this check

> Even best would be to actually check what happens on the server when such an import is launched multiple times and make sure its safely handled (the same user may endup imported in 2 different groups by 2 different admins, and in theory this can happen exactly at the same time) - but this is much much more advanced and can be handled as a separate issue.

it seems that something _is_ wrong in here, even if the probability that it happens becomes quite low if we disable the Import button.

**Comment by acotiuga** [comment]
Result:
![ImportingUsers](https://user-images.githubusercontent.com/8121819/115420342-bb8b4400-a203-11eb-9d1b-1b78053159e5.png)
