### ISSUE TITLE
Display a message when the number of results of the search is limited by the 20 (21) users limit

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-ldapuserimport#33]
This issue concerns the display of the search results when a search is performed in order to find users to import.
The number of results is capped at 21 (not really clear why 21, probably an off-by-one counting error when limiting).

The current behaviour is the following:
* open the import dialog
* search for users (in order to reproduce, a very generic search using a single letter (a or e) does the job)
* 21 results, both imported and not imported are displayed on the screen
  * these results are ordered alphabetically - but this ordering turns out to be done _after the capping to 21_, so they're not the first 21 results in alphabetical order, they are the first 21 results in random order (whatever order provided by the LDAP server), ordered afterwards.
  * this ordering is important, as it contributes significantly to the confusion (see below)
* there is no indication on the screen that the 21 results are not _all_ the results but only the "first" 21, so it's very hard for the user performing the import (admin) to understand why a user that they're expecting in the results is not "found" (it actually may be found but just not displayed because not in the first 21).
  * on large LDAP servers with many accounts it's probably more probable for this cap to be reached for a "normal" search, not only for a too generic search.

![image](https://user-images.githubusercontent.com/657716/120300196-ff29a100-c2cb-11eb-9b9a-5b7411656c20.png)

Expected result:
One easy palliation of this issue is to just provide feedback on the screen when the cap is reached, encouraging the importer to refine their search by adding details.
Note: the wording used when providing this cap needs to be very carefully chosen to avoid misleading the importer into believing that the 21 displayed results are the first 21 alphabetical results, as this is not true. Maybe we could drop the sorting alltogether if we don't find a coherent way to present this to users.

More advanced handling of the capping situation (but complex, I would say, and that would need new tickets) may include:
* giving priority to the accounts not yet imported when capping
  * in the current situation, accounts that are already imported may be displayed in the 21 results on the screen while accounts that are not imported yet may be left out, requiring a second more precise search. This is rather useless for the importer, they are searching for users in order to import them, so the fact that accounts for which no action is possible (the already imported users) have priority over account for which actions are possible (and probably desired).
* allowing the admin to configure the cap in the ldap user import configuration - this would be an easy solution to allow the admin to temporarily raise the limit in order to be able to find an account on LDAP, if there is no refinement possible for the search string.
* implementing a real pagination to allow access to all accounts.

**Comment by acotiuga** [comment]
What is fixed in this issue:
* the number for the results users is 20
* a new property was introduces to configure the number of users
* the users are ordered alphabetically by the configured UID
* the list of displayed user represents the first, alphabetically ordered, 20 users (imported and not imported)
* a message is displayed in the search modal:
![importMessage](https://user-images.githubusercontent.com/8121819/121328549-18120200-c91d-11eb-920e-31468ba48e5c.png)

**Comment by lucaa** [comment]
So, @acotiuga if I understand correctly from the last comment, the message is displayed all the time, not only when the limit is reached? And it's displayed on top of the search box not along with the search results? Is there any reason for this?

**Comment by acotiuga** [comment]
@lucaa the info message is displayed all the time, at the top of the search box and only the number of users displayed is variable. 
There is no particular reason for doing this, maybe just the simplicity of the solution for the given time-frame expectation, comparing to other possible solution suggested in the issue description.

**Comment by ldubost** [comment]
It seems that the sorting will require loading ALL users for a given query we would be a serious performance issue. I'm reopening this issue as we should make sure we only read the first "20" users and when reaching 20 we should display a message saying "There are more results in the LDAP server for this query. Please provide a more precise query"

**Comment by acotiuga** [comment]
What was changed after the last conversation:
* stop the LDAP entries iteration when reaching the configured limit, instead of fetching them all
* sort the results only when they are less than the limit
* move the information box along with the search results
