### ISSUE TITLE
Allow to import LDAP groups as XWiki groups

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-ldapuserimport#60]
The goal of this issue is to provide an API that would be responsible for importing LDAP groups that are currently not mapped in XWiki as XWiki equivalent groups.

**Comment by aubincleme** [comment]
The use-case is as follows : 
As an administrator of my XWiki instance, I may have a lot of LDAP groups already defined within my LDAP directory. I wish to configure these groups to be automatically created in XWiki, without having to go through the process of manually creating and mapping each group.

The first step of this issue is to provide a way to create the groups automatically in XWiki.
Then, the mapping that results from the import of the groups will need to be exposed to the LDAP extension API.

The parameters for the import can be the following : 
* The base DN on which groups should be searched
* A filter to use for searching the groups

**Comment by lucaa** [comment]
So, @aubincleme , if I understand correctly this feature:
* the possibility of setting up the sync of users for a group was already provided by this extension, but the admin needed to create the XWiki group manually each time and map it to the ldap group
* this change adds the possibility for the admin to do a one time import of groups from LDAP based on some sort of wildcard search (so that many can be added at once)
  * are the users from these groups also synced?
  * are these groups added to the automatic sync of users?
  * where is the UI for this new group sync feature?

**Comment by aubincleme** [comment]
Hei hei, 

> the possibility of setting up the sync of users for a group was already provided by this extension, but the admin needed to create the XWiki group manually each time and map it to the ldap group

Yes ; that's the goal of this sync

> this change adds the possibility for the admin to do a one time import of groups from LDAP based on some sort of wildcard search (so that many can be added at once) 

Kind of, it's a wildcard search by default (searching for every group defined in the LDAP directory), but the property `LDAP Group Import Search Filter` can be tuned down to sync only specific groups.

> are the users from these groups also synced?

No, that this the job of the LDAP user import. If the user import job is not enabled, the users will not be synced. However, if the user import job is enabled, then the users will be synced with the newly-created groups.

The two scheduler jobs (group import and user import) are configured so that one runs after the other : if the two are enabled, the group import job will first run, eventually creating new groups to sync, and then the user import job will run, to populate these groups.

> are these groups added to the automatic sync of users?

The newly created groups are registered in the LDAP group mapping, so if the automated sync is enabled, then the groups will be synced.

> where is the UI for this new group sync feature?

There's no UI, it's just a scheduler job.

In the meantime, I've updated the documentation of the Active Directory application on the store to better describe the feature. We still have to release a new version of the AD app integrating the latest version of the LDAP user import for this documentation to become generally available (see https://github.com/xwikisas/application-activedirectory/issues/74). Here is how it looks (currently the documentation is commented on the store page) : 

![image](https://github.com/xwikisas/application-ldapuserimport/assets/5938943/ac227219-737c-4946-acd5-297d2957a744)
